Services branch
Divo123-tech/DAM-server pull request #7
Opened 2024-05-10 03:59 UTC by Divo123-tech

2024-05-10 04:02 UTC, Divo123-tech commented
changes warehouseId to string because warehouse model hasn't been fixed yet, will change later

2024-05-10 06:07 UTC, yharsono requested changes

2024-05-10 06:07 UTC, yharsono commented on src/service/item.service.ts
> +        return await itemModel.find({isActive: true});
will this return _id? cause _id is not part of the ItemInterface?

2024-05-10 06:07 UTC, yharsono commented on src/controller/items.controller.ts
> +      res.status(200).json(await itemService.remove(req.body.id));
this should be part of params, not body. 
the URL should be: DELETE  /items/:itemId

2024-05-10 06:07 UTC, yharsono commented on src/controller/items.controller.ts
> +      res.status(200).json(await itemService.getAll());
nit: for readability, its better to do:
```
const items = await itemService.getAll()
res.status(200).json(items)
```

2024-05-10 06:07 UTC, yharsono commented on src/service/item.service.ts
> +        await itemModel.findByIdAndUpdate(id, {isActive: false}, {new:true})
why do you need to set {new:true} if the result is not actually being used?

2024-05-10 06:07 UTC, yharsono commented on src/models/items.model.ts
> +        type: String,
why is this not ObjectId?

2024-05-11 08:20 UTC, Divo123-tech commented
<h3>Removed DoesKodeExist Function</h3>
used .save to update or edit the function which now directly activates the validation making the DoesKodeExist function unnecessary. 

<h3>Added a modified Item Interface for the Front End </h3>
created an interface which has all the properties of the item interface without isActive, and used Object.assign to ensure that isActive cannot be modified from true unless its using the delete route.

<h3>Changed delete route</h3>
delete route now has id in the params not the body

2024-05-11 09:00 UTC, merged