Pagination branch
Divo123-tech/DAM-server pull request #8
Opened 2024-05-10 05:13 UTC by Divo123-tech

2024-05-10 06:13 UTC, yharsono requested changes

2024-05-10 06:13 UTC, yharsono commented on src/controller/items.controller.ts
> +        const skip: number = (Number(page) - 1) * Number(limit)
what if page and limit is not part of the query?
or what if there is only limit, but no page? or vice versa?

2024-05-10 06:13 UTC, yharsono commented on src/service/item.service.ts
> +        return await itemModel.find({isActive: true}).skip(skp || 0).limit(lmt || 10);
you should sort this by something to make sure you always get consistent result. 
Its better to also tell the FE the total counts of the actual list, so they know how many pages they can show

2024-05-10 17:16 UTC, yharsono requested changes

2024-05-11 06:16 UTC, yharsono requested changes

2024-05-11 06:16 UTC, yharsono commented on src/service/item.service.ts
> +    return items;
you are still not returning the count of all the items

2024-05-11 06:16 UTC, yharsono commented on src/service/item.service.ts
> +    // return newItem;
nit: remove unused code

2024-05-11 06:16 UTC, yharsono commented on src/utils/utils.ts
> +  //query validation implemented in this function
what query validation?

2024-05-11 06:16 UTC, yharsono commented on src/utils/utils.ts
> +export interface QueryInterface {
this is PaginationInterface, not QueryInterface

2024-05-11 06:16 UTC, yharsono commented on src/utils/utils.ts
> +  let skip: number = (page - 1) * limit; // Skip can be a number
const skip.

2024-05-11 06:25 UTC, Divo123-tech commented on src/service/item.service.ts
> +    return items;
should I make a new interface to return this kind of object?
{total:  number, data: items[]}

2024-05-11 06:42 UTC, yharsono requested changes

2024-05-11 06:42 UTC, yharsono commented on src/service/item.service.ts
> +    return { totalCount: items.length, data: items };
you cant just do items.lenght, cause its already been "limited" jdi this count will always return what the limit is, unless the amounts of items are smaller than the limit.

Check my previous comment on using $facet

2024-05-12 03:04 UTC, Divo123-tech commented
<h3>Added Multiple Aggregation to getAll function</h3>
used .facet() to avoid running multiple queries and return an object with the total number of items in the list that are active, and all the items according to the skip, limit and sort filters.

<h3>Accidentally Merged services-branch to main </h3>
Merged the changes of services-branch to this branch so the changes can be reviewed
<h4>Adding new item interface for the front end.</h4>
 Added this interface for the add and edit functions to use as inputs to avoid front end editing or adding certain properties.
<h4>Used .save() to activate validation</h4>
removed doesKodeExist as the function became unnecesarry after using .save()
<h4>Used Object methods like .assign and .definePropertry() </h4>
Object.assign() was to update the item, and .defineProperty() was to ensure that isActive can only be made false by delete not edit or add.
<h4>Changed delete route </h4>
Changed delete from accepting id in the body to using the request params.

2024-05-14 03:33 UTC, yharsono requested changes

2024-05-14 03:33 UTC, yharsono commented on src/service/item.service.ts
> +    Object.defineProperty(item, "isActive", {
I dont think we need to worry about this anymore now that we have the FEItemInterface. 
And you could just do: `itemToUpdate.isActive = true` to always set it to true

2024-05-14 03:33 UTC, yharsono commented on src/service/item.service.ts
> +    if (!itemToUpdate) {
you also need to check if `!itemToUpdate.isActive`, then you want to throw the item not found error, cause the item has been deleted

2024-05-14 03:33 UTC, yharsono commented on src/service/item.service.ts
> +    //assigns the ite passed to the item to be updated
nit: typo in the comment

2024-05-14 04:39 UTC, yharsono approved these changes

2024-05-14 04:40 UTC, merged